[package]
name        = "platform-basis"
description = "Flix wrappers over the JDK modules"
version     = "0.2.0"
flix        = "0.40.0"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]

[dependencies]
"github:stephentetley/charset-locale"           = "0.1.0"

